Restore is broken... working on it

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -56,25 +56,33 @@ EOF
 # Run a command in the container. 
 
 function dockerrun {
-   docker run -i -t --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" "${IMAGENAME}" "$@"
-   local RVAL=$?
+   local RVAL=0
+   docker run "${COMMANDOPTS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" "${IMAGENAME}" "$@"
+   RVAL=$?
    docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
-   if [ $RVAL -ne 0 ]; then die "${SERVICENAME} ${COMMAND} failed." ; fi
+   [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
 }
 
 #------------------------------------------------------------------------------------
-# See if a container is running
+# See if a container is exists. Return value of docker inspect is correct (0 if running)
 # https://gist.github.com/ekristen/11254304
 
 function container_exists {
    # exit code of docker inspect says if it's running.
    docker inspect --format="{{ .State.Running }}" "$1" >/dev/null 2>&1
 }
+
+#------------------------------------------------------------------------------------
+# See if a container is running
+
 function container_running {
    container_exists "$1" || return 1
    local RUNNING=$(docker inspect --format="{{ .State.Running }}" "$1" 2>/dev/null)
    [ "${RUNNING}" = "true" ]
 }
+
+#------------------------------------------------------------------------------------
+# Get the port from the configuration file.
 
 function getPort {
    PORT=$(docker run -i --name="${SERVICENAME}-getport" ${DOCKEROPTS[@]} ${IMAGENAME} bash -c "cat /config/port")
@@ -84,10 +92,15 @@ function getPort {
    [ -n "$PORT" ] || die "Run configure first!"
 }
 
+#------------------------------------------------------------------------------------
+# Determine the host ip. See http://stackoverflow.com/a/25851186
+
 function getHostIP {
-   # http://stackoverflow.com/a/25851186
    HOSTIP=$(ip route get 1 | awk '{print $NF;exit}')
 }
+
+#------------------------------------------------------------------------------------
+# Display the status of hte service.
 
 function showStatus {
    container_exists "${SERVICENAME}-run"  || { echo "${SERVICENAME}'s container does not exist." ; exit 0 ; }
@@ -95,6 +108,32 @@ function showStatus {
    getPort
    getHostIP
    echo "Minecraft is running on ${HOSTIP}:${PORT}"   
+}
+
+#------------------------------------------------------------------------------------
+# Stop the service if it's running. TODO: Exit 3 on no change.
+
+function stop {
+   ! container_running "${SERVICENAME}-run" || docker stop --time=30 "${SERVICENAME}-run" >/dev/null 2>&1
+   ! container_exists "${SERVICENAME}-run"  || docker rm "${SERVICENAME}-run" >/dev/null 2>&1
+   showStatus   
+}
+
+#------------------------------------------------------------------------------------
+# Start the service if it's not running. Exits 3 on no change.
+
+function start {
+   ! container_running "${SERVICENAME}-run" || die "Already running" 3 
+   ! container_exists "${SERVICENAME}-run"  || docker rm "${SERVICENAME}-run" >/dev/null 2>&1
+
+   getPort
+
+   # Run the service. 
+   # DOCKEROPTS, SERVICENAME AND IMAGENAME are set by _variables.
+   COMMANDOPTS=("-d" "-p=${PORT}:25565" "-p=${PORT}:25565/udp" "--restart=always")
+   dockerrun java -jar /minecraft_server.1.8.7.jar                          
+   [ $? -eq 0 ] || die "Failed to launch minecraft on port $PORT :("
+   showStatus
 }
 
 #------------------------------------------------------------------------------------
@@ -113,11 +152,28 @@ function main {
             ;;
                      
          backup)
+            # data volume is automatically hot backed up. We are paranoid here, taking a paused
+            # backup as well. Probably don't need this for minecraft, but good as an example.
+            # This does mean the backup set contains both hot + paused backups, doubling the data
+            # size. Could avoid this by managing the data container ourselves (not listing it in
+            # service.cfg), but minecraft data is small so we don't care.
             BACKUPPATH="$1"
+            STARTED=1
+            container_running "${SERVICENAME}-run" && STARTED=0 && docker pause "${SERVICENAME}-run"
+            COMMANDOPTS=("-i" "-v" "${BACKUPPATH}:/backups")
+            dockerrun bash -c 'tar zcf /backups/databackup.tgz /data'
+            [ -e "${BACKUPPATH}/databackup.tgz" ] || die "Failed to create cold backup of minecraft data volume."
+            [ STARTED -eq 1 ] || docker unpause "${SERVICENAME}-run" 
             ;;
          
          restore)
+            # cold restore.
             RESTOREPATH="$1"
+            ! container_running "${SERVICENAME}-run" || die "Can't restore into a running container!"
+            [ -e "${RESTOREPATH}/databackup.tgz" ] || { ls "${RESTOREPATH}" ; die "Restore path does not contain the data volume backup." }
+            COMMANDOPTS=("-i" "-v" "${RESTOREPATH}:/backups")
+            # could compare hot + paused backups if we wanted here. We just throw away the hot one.
+            dockerrun bash -c 'rm -r /data/* && tar zxf /backups/databackup.tgz'
             ;;
          
          help)
@@ -132,36 +188,21 @@ function main {
             ;;
 
          start)
-            ! container_running "${SERVICENAME}-run" || die "Already running" 3 
-            ! container_exists "${SERVICENAME}-run"  || docker rm "${SERVICENAME}-run" >/dev/null 2>&1
-
-            getPort
-
-            # Run the service. 
-            # DOCKEROPTS, SERVICENAME AND IMAGENAME are set by _variables.
-            docker run -d=true --name="${SERVICENAME}-run" -h "${HOSTNAME}"              \
-                           ${DOCKEROPTS[@]}  -p="${PORT}:25565" -p="${PORT}:25565/udp"   \
-                           ${IMAGENAME} java -jar /minecraft_server.1.8.7.jar                          
-            [ $? -eq 0 ] || die "Failed to launch minecraft on port $PORT :("
-            showStatus
+            start
             ;;
          
          configure)
             ! container_running "${SERVICENAME}-run" || die "Can't configure while ${SERVICENAME} is started. Stop it first."
             [ "$#" -eq 1 ] || { showhelp ; die "You need to specify the PORT."; }
             PORT="$1"
-
-            docker run -i --name="${SERVICENAME}-configure" ${DOCKEROPTS[@]} ${IMAGENAME} bash -c "echo -n $PORT > /config/port && echo eula=true > /data/eula.txt"
-            RVAL=$?
-            docker rm "${SERVICENAME}-configure" >/dev/null 2>&1
-            [ "$RVAL" -eq 0 ] || die "Failed to configure minecraft on port $PORT :("
+            
+            COMMANDOPTS=("-i")
+            dockerrun bash -c "echo -n $PORT > /config/port && echo eula=true > /data/eula.txt"
             ;;
 
          stop)
             # check if running, if so stop it.
-            ! container_running "${SERVICENAME}-run" || docker stop --time=30 "${SERVICENAME}-run" >/dev/null 2>&1
-            ! container_exists "${SERVICENAME}-run"  || docker rm "${SERVICENAME}-run" >/dev/null 2>&1
-            showStatus
+            stop
             ;;
          
          status)
